# zkBricks site
title: zkBricks
description: "Translating cutting-edge cryptography into practical tools for privacy, safety, and trust in digital systems. Open-source public goods."
url: "https://zkbricks.github.io"
baseurl: ""
author: zkBricks
authors:
  - Arka Rai Chaudhary
  - Sanjam Garg

# Build
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - vendor

